### ISSUE TITLE
Error submitting a packet for decoding!

### ISSUE THREAD

**Issue by songiang95** [lincollincol/Amplituda#56]
I has an issue when process long mp3 file (over 1 hour) download from youtube via (https://www.y2mate.com/). Please take a look.

**Comment by lincollincol** [comment]
@songiang95 Hello! Please, provide error logs or youtube video url

**Comment by songiang95** [comment]
> @songiang95 Hello! Please, provide error logs or youtube video url
Video url: https://www.youtube.com/watch?v=NP5NAwRZm0k
I download audio of this video via https://www.y2mate.com/

Log:
`2022-12-21 09:08:22.005 16394-16394/linc.com.example I/System.out: Start Progress
2022-12-21 09:08:22.006 16394-16394/linc.com.example E/AMPLITUDA: Process audio /storage/emulated/0/nonstop3.mp3
2022-12-21 09:08:22.373 16394-16394/linc.com.example D/abba: progres: 1
2022-12-21 09:08:22.375 16394-16394/linc.com.example I/System.out: Process audio: 1% 
2022-12-21 09:08:22.737 16394-16394/linc.com.example D/abba: progres: 2
2022-12-21 09:08:22.738 16394-16394/linc.com.example I/System.out: Process audio: 2% 
2022-12-21 09:08:23.090 16394-16394/linc.com.example D/abba: progres: 3
2022-12-21 09:08:23.091 16394-16394/linc.com.example I/System.out: Process audio: 3% 
2022-12-21 09:08:23.442 16394-16394/linc.com.example D/abba: progres: 4
2022-12-21 09:08:23.443 16394-16394/linc.com.example I/System.out: Process audio: 4% 
2022-12-21 09:08:23.795 16394-16394/linc.com.example D/abba: progres: 5
2022-12-21 09:08:23.796 16394-16394/linc.com.example I/System.out: Process audio: 5% 
2022-12-21 09:08:24.147 16394-16394/linc.com.example D/abba: progres: 6
2022-12-21 09:08:24.148 16394-16394/linc.com.example I/System.out: Process audio: 6% 
2022-12-21 09:08:24.499 16394-16394/linc.com.example D/abba: progres: 7
2022-12-21 09:08:24.500 16394-16394/linc.com.example I/System.out: Process audio: 7% 
2022-12-21 09:08:24.852 16394-16394/linc.com.example D/abba: progres: 8
2022-12-21 09:08:24.853 16394-16394/linc.com.example I/System.out: Process audio: 8% 
2022-12-21 09:08:25.203 16394-16394/linc.com.example D/abba: progres: 9
2022-12-21 09:08:25.204 16394-16394/linc.com.example I/System.out: Process audio: 9% 
2022-12-21 09:08:25.556 16394-16394/linc.com.example D/abba: progres: 10
2022-12-21 09:08:25.557 16394-16394/linc.com.example I/System.out: Process audio: 10% 
2022-12-21 09:08:25.909 16394-16394/linc.com.example D/abba: progres: 11
2022-12-21 09:08:25.911 16394-16394/linc.com.example I/System.out: Process audio: 11% 
2022-12-21 09:08:26.262 16394-16394/linc.com.example D/abba: progres: 12
2022-12-21 09:08:26.263 16394-16394/linc.com.example I/System.out: Process audio: 12% 
2022-12-21 09:08:26.445 16394-16394/linc.com.example D/abba: progres: 100
2022-12-21 09:08:26.446 16394-16394/linc.com.example I/System.out: Process audio: 100% 
2022-12-21 09:08:26.447 16394-16394/linc.com.example E/AMPLITUDA: Processing time: 4.4400 seconds
2022-12-21 09:08:26.447 16394-16394/linc.com.example I/System.out: Stop Progress
2022-12-21 09:08:26.449 16394-16394/linc.com.example W/System.err: linc.com.amplituda.exceptions.processing.PacketSubmittingException: Error submitting a packet for decoding!
2022-12-21 09:08:26.449 16394-16394/linc.com.example W/System.err: Read Amplituda doc here: https://github.com/lincollincol/Amplituda
2022-12-21 09:08:26.449 16394-16394/linc.com.example W/System.err:     at linc.com.amplituda.AmplitudaResultJNI.getExceptionFromCode(AmplitudaResultJNI.java:105)
2022-12-21 09:08:26.449 16394-16394/linc.com.example W/System.err:     at linc.com.amplituda.AmplitudaResultJNI.getErrors(AmplitudaResultJNI.java:85)
2022-12-21 09:08:26.449 16394-16394/linc.com.example W/System.err:     at linc.com.amplituda.AmplitudaProcessingOutput.<init>(AmplitudaProcessingOutput.java:32)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:364)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:218)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at linc.com.example.MainActivity.onCreate(MainActivity.java:27)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.app.Activity.performCreate(Activity.java:7383)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.app.ActivityThread.-wrap12(Unknown Source:0)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:108)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.os.Looper.loop(Looper.java:166)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7529)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
2022-12-21 09:08:26.450 16394-16394/linc.com.example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)`

**Comment by fus3rx** [comment]
W/System.err: linc.com.amplituda.exceptions.processing.PacketSubmittingException: Error submitting a packet for decoding!
W/System.err: Read Amplituda doc here: https://github.com/lincollincol/Amplituda
W/System.err:     at linc.com.amplituda.AmplitudaResultJNI.getExceptionFromCode(AmplitudaResultJNI.java:105)
W/System.err:     at linc.com.amplituda.AmplitudaResultJNI.getErrors(AmplitudaResultJNI.java:85)
W/System.err:     at linc.com.amplituda.AmplitudaProcessingOutput.<init>(AmplitudaProcessingOutput.java:32)
W/System.err:     at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:394)
W/System.err:     at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:74)
W/System.err:     at com.masoudss.lib.utils.WaveformOptions.getSampleFrom(WaveformOptions.kt:13)
W/System.err:     at com.masoudss.lib.WaveformSeekBar.setSampleFrom(WaveformSeekBar.kt:220)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by PepaZapletal** [comment]
Hi, 

Im getting the same error: PacketSubmittingException: Error submitting a packet for decoding!

```
linc.com.amplituda.exceptions.processing.PacketSubmittingException: Error submitting a packet for decoding!
Read Amplituda doc here: https://github.com/lincollincol/Amplituda
at linc.com.amplituda.AmplitudaResultJNI.getExceptionFromCode(AmplitudaResultJNI.java:105)
at linc.com.amplituda.AmplitudaResultJNI.getErrors(AmplitudaResultJNI.java:85)
at linc.com.amplituda.AmplitudaProcessingOutput.<init>(AmplitudaProcessingOutput.java:32)
at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:429)
at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:78)
```

Using this sample code:

```
                            Amplituda amplituda = new Amplituda(getContext());
                            amplituda.setLogConfig(Log.DEBUG, true);

                            try {
                                // Load an audio file from the app's resources
                                amplituda.processAudio(R.raw.sample)
                                        .get(result -> {
                                            List<Integer> amplitudesData = result.amplitudesAsList();
                                            // etc
                                        }, exception -> {
                                            exception.printStackTrace();

                                            if(exception instanceof AmplitudaIOException) {
                                                System.out.println("IO Exception!");
                                            }
                                        });
                            } catch (Exception e) {
                                e.printStackTrace();
                                // Handle the exception
                            }
```

And this is sample.mp3 file: https://drive.google.com/file/d/1eKitHAdx8dbf5PvN_BOoycuJledbbpZn/view?usp=sharing

What Im doing wrong? What should I set?

Thank you for info!

**Comment by thirumalVenket12** [comment]
Am also having the same issue which is posted above one.

am fetching the wave from the MP3 file it's having the same issue 


linc.com.amplituda.exceptions.processing.PacketSubmittingException: Error submitting a packet for decoding!
2024-01-24 12:52:02.552 27884-27884 System.err                                    W  Read Amplituda doc here: https://github.com/lincollincol/Amplituda
2024-01-24 12:52:02.553 27884-27884 System.err                                   W  	at linc.com.amplituda.AmplitudaResultJNI.getExceptionFromCode(AmplitudaResultJNI.java:105)
2024-01-24 12:52:02.553 27884-27884 System.err                                    W  	at linc.com.amplituda.AmplitudaResultJNI.getErrors(AmplitudaResultJNI.java:85)
2024-01-24 12:52:02.553 27884-27884 System.err                                   W  	at linc.com.amplituda.AmplitudaProcessingOutput.<init>(AmplitudaProcessingOutput.java:32)
2024-01-24 12:52:02.553 27884-27884 System.err                                    W  	at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:364)
2024-01-24 12:52:02.553 27884-27884 System.err                                    W  	at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:74)
2024-01-24 12:52:02.553 27884-27884 System.err                                    W  	at com.masoudss.lib.utils.WaveformOptions.getSampleFrom(WaveformOptions.kt:13)
2024-01-24 12:52:02.553 27884-27884 System.err                                    W  	at com.masoudss.lib.WaveformSeekBar.setSampleFrom(WaveformSeekBar.kt:226)

**Comment by thirumalVenket12** [comment]
> Am also having the same issue which is posted above one.
> 
> am fetching the wave from the MP3 file it's having the same issue
> 
> linc.com.amplituda.exceptions.processing.PacketSubmittingException: Error submitting a packet for decoding! 2024-01-24 12:52:02.552 27884-27884 System.err W Read Amplituda doc here: https://github.com/lincollincol/Amplituda 2024-01-24 12:52:02.553 27884-27884 System.err W at linc.com.amplituda.AmplitudaResultJNI.getExceptionFromCode(AmplitudaResultJNI.java:105) 2024-01-24 12:52:02.553 27884-27884 System.err W at linc.com.amplituda.AmplitudaResultJNI.getErrors(AmplitudaResultJNI.java:85) 2024-01-24 12:52:02.553 27884-27884 System.err W at linc.com.amplituda.AmplitudaProcessingOutput.(AmplitudaProcessingOutput.java:32) 2024-01-24 12:52:02.553 27884-27884 System.err W at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:364) 2024-01-24 12:52:02.553 27884-27884 System.err W at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:74) 2024-01-24 12:52:02.553 27884-27884 System.err W at com.masoudss.lib.utils.WaveformOptions.getSampleFrom(WaveformOptions.kt:13) 2024-01-24 12:52:02.553 27884-27884 System.err W at com.masoudss.lib.WaveformSeekBar.setSampleFrom(WaveformSeekBar.kt:226)

@lincollincol any update on the above issue

**Comment by ArturMazay** [comment]
Тоже такая ошибка вылетает, пофиксите?
