### ISSUE TITLE
AmplitudaResult.amplitudesAsList: NumberFormatException

### ISSUE THREAD

**Issue by Lampotrias** [lincollincol/Amplituda#66]
Hi. I see crash at the Firebase:

```
Fatal Exception: java.lang.NumberFormatException: For input string: "duration=1.724082"
       at java.lang.Integer.parseInt(Integer.java:615)
       at java.lang.Integer.valueOf(Integer.java:801)
       at linc.com.amplituda.AmplitudaResult.amplitudesAsList(AmplitudaResult.java:65)
.....
```

Problem file below:
https://drive.google.com/file/d/1nnrBq0ghTGa03TDsgCVMjjQ9VM_hicnN/view?usp=sharing

**Smartphone (please complete the following information):**
Android 10, Honor 20 PRO

**Comment by lincollincol** [comment]
Sample project output:
```
source = /storage/emulated/0/Music/1.mp3
source type = PATH
  
Amplitudes:
size: = 65
list: = [0, 0, 5, 13, 26, 40, 24, 9, 9, 13, 15, 11, 16, 17, 13, 8, 9, 15, 13, 9, 9, 3, 8, 13, 17, 17, 10, 6, 11, 12, 13, 11, 7, 8, 8, 8, 8, 2, 6, 11, 11, 11, 6, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

Tested on version `2.3.0`
