### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError linc.com.amplituda.Amplituda

### ISSUE THREAD

**Issue by BuiDucHai-dev** [lincollincol/Amplituda#67]
Hi team, 
I see some trouble at Firebase

Caused by java.lang.UnsatisfiedLinkError: dlopen failed: library "libamplituda-native-lib.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
       at java.lang.System.loadLibrary(System.java:1661)
       at linc.com.amplituda.Amplituda.<clinit>(Amplituda.java:612)

It looks like there is some issue in native code. Can you please help with this?

**Comment by asayushg** [comment]
Hello @BuiDucHai-dev I am also getting the same error. Have you fixed it?
